FROM silkeh/clang:21

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        cmake \
        git \
        libpq-dev \
        libssl-dev \
        ninja-build \
        pkg-config \
        zlib1g-dev \
        meson \                  # ← this is what you need
        python3-venv \           # helps meson on Debian
    && rm -rf /var/lib/apt/lists/*

# test