FROM jetbrains/qodana-clang:2024.1-eap

# Update the package lists and install necessary packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl sudo ca-certificates && \
    rm -rf /var/lib/apt/lists/*

RUN curl https://raw.githubusercontent.com/spiritEcosse/aws-sailfish-sdk/master/install.sh | bash -s -- --func=foxy_sever_libs
COPY . /data/project/
RUN export BUILD_FOLDER=/data/project/build; export SRC=/data/project/; \
    curl https://raw.githubusercontent.com/spiritEcosse/aws-sailfish-sdk/master/install.sh | bash -s -- --func='cmake_build'
