FROM ubuntu:22.04 as build
# Update the package lists and install necessary packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl sudo ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# Run the install scripts
RUN curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/spiritEcosse/aws-sailfish-sdk/master/install.sh | bash -s -- --func=foxy_sever_libs
RUN mkdir -p /data/project/
COPY . /data/project/
RUN export BUILD_FOLDER=/data/project/build; export SRC=/data/project/; \
    curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/spiritEcosse/aws-sailfish-sdk/master/install.sh | bash -s -- --func='cmake_build'; \
    curl -H 'Cache-Control: no-cache' curl https://raw.githubusercontent.com/spiritEcosse/aws-sailfish-sdk/master/install.sh | bash -s -- --func='remove_folders_from_compile_commands'

FROM jetbrains/qodana-clang:latest

# Copy the files
COPY --from=build /data/project/ /data/project/
