services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pg_socket:/var/run/postgresql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./helper.sql:/docker-entrypoint-initdb.d/helper.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  foxy-prod:
    image: ghcr.io/spiritecosse/foxy_server:main
    container_name: foxy-prod
    hostname: foxy_prod
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pg_socket:/var/run/postgresql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.foxy-prod.rule=Host(`api.faithfishart.com`)"
      - "traefik.http.routers.foxy-prod.entrypoints=websecure"
      - "traefik.http.routers.foxy-prod.tls.certresolver=letsencrypt"
    networks:
      - web
      - backend

  foxy-dev:
    image: ghcr.io/spiritecosse/foxy_server:dev
    container_name: foxy-dev
    hostname: foxy_dev
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pg_socket:/var/run/postgresql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.foxy-dev.rule=Host(`dev-api.faithfishart.com`)"
      - "traefik.http.routers.foxy-dev.entrypoints=websecure"
      - "traefik.http.routers.foxy-dev.tls.certresolver=letsencrypt"
    networks:
      - web
      - backend

volumes:
  pgdata:
  pg_socket:

networks:
  web:
    external: true
  backend:
    driver: bridge
