FROM silkeh/clang:21

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        cmake \
        git \
        libpq-dev \
        libssl-dev \
        ninja-build \
        pkg-config \
        uuid-dev \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*
