x-db: &db foxy

services:

  postgres:
    image: postgres:17-alpine
    container_name: postgres-${PROFILE}
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: *db
      POSTGRES_DB: *db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pg_socket:/var/run/postgresql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: ghcr.io/spiritecosse/foxy_server:${TAG}
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
    command: atlas migrate apply --env ${PROFILE}
    volumes:
      - pg_socket:/var/run/postgresql
    working_dir: /app
    networks:
      - backend

  foxy:
    image: ghcr.io/spiritecosse/foxy_server:${TAG}
    container_name: foxy-${PROFILE}
    restart: always
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      FOXY_CLIENT: ${FOXY_CLIENT}
      FOXY_ADMIN: ${FOXY_ADMIN}
      APP_CLOUD_NAME: ${APP_CLOUD_NAME}
      APP_BUCKET_HOST: ${APP_BUCKET_HOST}
      PINTEREST_API_HOST: ${PINTEREST_API_HOST}
      PINTEREST_BOARD_ID: ${PINTEREST_BOARD_ID}
      PINTEREST_CLIENT_ID: ${PINTEREST_CLIENT_ID}
      PINTEREST_CLIENT_SECRET: ${PINTEREST_CLIENT_SECRET}
      YOUTUBE_REFRESH_TOKEN: ${YOUTUBE_REFRESH_TOKEN}
      YOUTUBE_CLIENT_ID: ${YOUTUBE_CLIENT_ID}
      YOUTUBE_CLIENT_SECRET: ${YOUTUBE_CLIENT_SECRET}
      TWITTER_API_KEY: ${TWITTER_API_KEY}
      TWITTER_API_SECRET: ${TWITTER_API_SECRET}
      TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_TOKEN_SECRET: ${TWITTER_ACCESS_TOKEN_SECRET}
      TWITTER_BEARER_TOKEN: ${TWITTER_BEARER_TOKEN}
      PG_DB: *db
      PG_USER: *db
    volumes:
      - pg_socket:/var/run/postgresql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.foxy-${PROFILE}.rule=Host(`${HOST}`)"
      - "traefik.http.routers.foxy-${PROFILE}.entrypoints=${ENTRYPOINT}"
      - "traefik.http.routers.foxy-${PROFILE}.tls.certresolver=letsencrypt"
    networks:
      - web
      - backend

volumes:
  pgdata:
    name: foxy_pgdata_${PROFILE}
  pg_socket:
    name: foxy_pg_socket_${PROFILE}

networks:
  web:
    external: true
  backend:
    driver: bridge
