/**
 *
 *  Image.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Image.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::foxy;

const std::string Image::Cols::_id = "id";
const std::string Image::Cols::_original = "original";
const std::string Image::Cols::_item_id = "item_id";
const std::string Image::primaryKeyName = "id";
const bool Image::hasPrimaryKey = true;
const std::string Image::tableName = "image";

const std::vector<typename Image::MetaData> Image::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"original","std::string","character varying",255,0,0,1},
{"item_id","int32_t","integer",4,0,0,1}
};
const std::string &Image::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Image::Image(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["original"].isNull())
        {
            original_=std::make_shared<std::string>(r["original"].as<std::string>());
        }
        if(!r["item_id"].isNull())
        {
            itemId_=std::make_shared<int32_t>(r["item_id"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            original_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            itemId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Image::Image(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            original_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            itemId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

Image::Image(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("original"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["original"].isNull())
        {
            original_=std::make_shared<std::string>(pJson["original"].asString());
        }
    }
    if(pJson.isMember("item_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["item_id"].isNull())
        {
            itemId_=std::make_shared<int32_t>((int32_t)pJson["item_id"].asInt64());
        }
    }
}

void Image::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            original_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            itemId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

void Image::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("original"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["original"].isNull())
        {
            original_=std::make_shared<std::string>(pJson["original"].asString());
        }
    }
    if(pJson.isMember("item_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["item_id"].isNull())
        {
            itemId_=std::make_shared<int32_t>((int32_t)pJson["item_id"].asInt64());
        }
    }
}

const int32_t &Image::getValueOfId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Image::getId() const noexcept
{
    return id_;
}
void Image::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Image::PrimaryKeyType & Image::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Image::getValueOfOriginal() const noexcept
{
    const static std::string defaultValue = std::string();
    if(original_)
        return *original_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Image::getOriginal() const noexcept
{
    return original_;
}
void Image::setOriginal(const std::string &pOriginal) noexcept
{
    original_ = std::make_shared<std::string>(pOriginal);
    dirtyFlag_[1] = true;
}
void Image::setOriginal(std::string &&pOriginal) noexcept
{
    original_ = std::make_shared<std::string>(std::move(pOriginal));
    dirtyFlag_[1] = true;
}

const int32_t &Image::getValueOfItemId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(itemId_)
        return *itemId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Image::getItemId() const noexcept
{
    return itemId_;
}
void Image::setItemId(const int32_t &pItemId) noexcept
{
    itemId_ = std::make_shared<int32_t>(pItemId);
    dirtyFlag_[2] = true;
}

void Image::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Image::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "original",
        "item_id"
    };
    return inCols;
}

void Image::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getOriginal())
        {
            binder << getValueOfOriginal();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getItemId())
        {
            binder << getValueOfItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Image::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void Image::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getOriginal())
        {
            binder << getValueOfOriginal();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getItemId())
        {
            binder << getValueOfItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Image::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getOriginal())
    {
        ret["original"]=getValueOfOriginal();
    }
    else
    {
        ret["original"]=Json::Value();
    }
    if(getItemId())
    {
        ret["item_id"]=getValueOfItemId();
    }
    else
    {
        ret["item_id"]=Json::Value();
    }
    return ret;
}

Json::Value Image::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getOriginal())
            {
                ret[pMasqueradingVector[1]]=getValueOfOriginal();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getItemId())
            {
                ret[pMasqueradingVector[2]]=getValueOfItemId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getOriginal())
    {
        ret["original"]=getValueOfOriginal();
    }
    else
    {
        ret["original"]=Json::Value();
    }
    if(getItemId())
    {
        ret["item_id"]=getValueOfItemId();
    }
    else
    {
        ret["item_id"]=Json::Value();
    }
    return ret;
}

bool Image::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("original"))
    {
        if(!validJsonOfField(1, "original", pJson["original"], err, true))
            return false;
    }
    else
    {
        err="The original column cannot be null";
        return false;
    }
    if(pJson.isMember("item_id"))
    {
        if(!validJsonOfField(2, "item_id", pJson["item_id"], err, true))
            return false;
    }
    else
    {
        err="The item_id column cannot be null";
        return false;
    }
    return true;
}
bool Image::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Image::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("original"))
    {
        if(!validJsonOfField(1, "original", pJson["original"], err, false))
            return false;
    }
    if(pJson.isMember("item_id"))
    {
        if(!validJsonOfField(2, "item_id", pJson["item_id"], err, false))
            return false;
    }
    return true;
}
bool Image::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Image::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
