sonar.organization=spiritecosse
sonar.projectKey=spiritEcosse_foxy_server
sonar.projectName=foxy_server
sonar.protectedBranches=dev,main

sonar.sources=.
sonar.language=cpp
sonar.cfamily.compile-commands=bw-output/compile_commands.json
sonar.cfamily.cache.enabled=true
sonar.cfamily.threads=4
sonar.sourceEncoding=UTF-8

sonar.exclusions=build/**,cmake-build-debug/**,tests/**
sonar.coverage.exclusions=build/**,cmake-build-debug/**,tests/**
sonar.cpd.exclusions=build/**,cmake-build-debug/**,tests/**
