on:
  push:
    branches:
      - '*'
  workflow_call:
    secrets:
      CR_PAT:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u spiritEcosse --password-stdin

      - name: Pull build image
        id: pull_build_image
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q "Dockerfile.build"; then
            echo "exists=false" >> $GITHUB_OUTPUT
          else
            docker pull ghcr.io/spiritecosse/foxy_server_build:${BRANCH_NAME} && echo "exists=true" >> $GITHUB_OUTPUT || echo "exists=false" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Build and push build image
        if: steps.pull_build_image.outputs.exists != 'true'
        run: |
          docker build -f Dockerfile.build -t ghcr.io/spiritecosse/foxy_server_build:${BRANCH_NAME} .
          docker push ghcr.io/spiritecosse/foxy_server_build:${BRANCH_NAME}

      - name: Build runtime image
        run: |
          cat > .env.build <<EOF
          APP_CLOUD_NAME=${{ vars.APP_CLOUD_NAME }}
          APP_BUCKET_HOST=${{ vars.APP_BUCKET_HOST }}
          FOXY_ADMIN=${{ vars.FOXY_ADMIN }}
          FOXY_CLIENT=${{ vars.FOXY_CLIENT }}
          ENVIRONMENT=${{ vars.ENVIRONMENT }}
          PINTEREST_API_HOST=${{ vars.PINTEREST_API_HOST }}
          PINTEREST_BOARD_ID=${{ vars.PINTEREST_BOARD_ID }}
          PINTEREST_REFRESH_TOKEN=${{ secrets.PINTEREST_REFRESH_TOKEN }}
          PINTEREST_CLIENT_ID=${{ vars.PINTEREST_CLIENT_ID }}
          PINTEREST_CLIENT_SECRET=${{ secrets.PINTEREST_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN=${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          YOUTUBE_CLIENT_ID=${{ vars.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET=${{ secrets.YOUTUBE_CLIENT_SECRET }}
          TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_BEARER_TOKEN=${{ secrets.TWITTER_BEARER_TOKEN }}
          EOF
          docker build \
            -t ghcr.io/spiritecosse/foxy_server:${BRANCH_NAME} \
            --build-arg BRANCH_NAME="${BRANCH_NAME}" \
            --secret id=env,src=.env.build \
            .

      - name: Push runtime image
        run: docker push ghcr.io/spiritecosse/foxy_server:${BRANCH_NAME}
