on:
  push:
    branches:
      - '*'
  workflow_call:
    secrets:
      CR_PAT:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # Recommended for paths-filter

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u spiritEcosse --password-stdin

      - name: Check if Dockerfile.build changed
        id: changed
        uses: dorny/paths-filter@v4
        with:
          filters: |
            dockerfile:
              - 'Dockerfile.build'

      - name: Pull build image (if exists)
        id: pull_build_image
        if: steps.changed.outputs.dockerfile != 'true'
        run: |
          if docker pull ghcr.io/spiritecosse/foxy_server_build:${BRANCH_NAME}; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Build new build image
        if: steps.changed.outputs.dockerfile == 'true' || steps.pull_build_image.outputs.exists != 'true'
        run: |
          docker build -f Dockerfile.build \
                       -t ghcr.io/spiritecosse/foxy_server_build:${BRANCH_NAME} .
          docker push ghcr.io/spiritecosse/foxy_server_build:${BRANCH_NAME}

      - name: Build runtime image
        run: |
          docker build \
            -t ghcr.io/spiritecosse/foxy_server:${BRANCH_NAME} \
            --build-arg BRANCH_NAME="${BRANCH_NAME}" \
            .

      - name: Push runtime image
        run: docker push ghcr.io/spiritecosse/foxy_server:${BRANCH_NAME}
