name: CMake Build


on:
    push:
        branches:
            - '*'

jobs:
    build:
        runs-on: ubuntu-22.04 # Must be the same as on server

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: CMake Build
              env:
                  SRC_FOLDER_NAME: 'work/foxy_server/foxy_server'
              run: curl https://spiritecosse.github.io/aws-sailfish-sdk/install.sh | bash -s -- --func='cmake_build'
