name: Cppcheck
on: [ push, pull_request ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4.1.6
            -   name: Run Cppcheck
                uses: deep5050/cppcheck-action@v3.0
                with:
                    check-command: 'cppcheck --enable=all .'
