name: deploy

on:
  workflow_run:
    workflows: ["build"]
    branches: [main, dev]
    types: [completed]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'dev'

jobs:
  deploy-dev:
    if: >
      (github.event_name == 'workflow_dispatch' && github.event.inputs.branch == 'dev') ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'dev')
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      tag: dev
      env_name: dev

  deploy-prod:
    if: >
      (github.event_name == 'workflow_dispatch' && github.event.inputs.branch == 'main') ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main')
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      tag: main
      env_name: prod
