name: Qodana
on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - "*"

jobs:
    qodana:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            checks: write
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Build Docker image
                id: build_image
                run: |
                    docker build -t qodana_image -f Dockerfile_qodana .

            -   name: 'Qodana Scan'
                uses: docker://qodana_image
                env:
                    QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
