name: Qodana
on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - "*"

jobs:
    build:
        uses: ./.github/workflows/build.yml
        secrets:
            CR_PAT: ${{ secrets.CR_PAT }}

    qodana:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            checks: write
        steps:
            -   name: 'Qodana Scan'
                uses: JetBrains/qodana-action@v2024.1
                with:
                    args: -l,jetbrains/qodana-clang:latest
                env:
                    QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
