name: Qodana
on:
    workflow_dispatch:
    push:
        branches:
            - "*"

jobs:
    qodana:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            checks: write
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: 'Qodana Scan'
                uses: JetBrains/qodana-action@v2024.1
                env:
                    QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
                with:
                    pr-mode: false
                    args: --apply-fixes
                    push-fixes: pull-request
